name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run tests
      run:  bundle exec rake test
